title: JWK(S) Tools and Generator CLI
description: A .NET Global tool utility for helping create JWK and JWKS based on certificate files.
show_downloads: true
nuget:
  show_nuget: true
  nuget_url: https://www.nuget.org/packages/jwks.tools/
show_nuget: true
theme: jekyll-theme-cayman
github:
  zip_url: https://github.com/johnmcbride/jwks.tools/archive/refs/heads/main.zip

# lsi: false
# safe: true
# source: https://github.com/johnmcbride/jwks.tools
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
# github:
#   zip_url: http://example.com/download.zip
#   another_url: another value
# theme: jekyll-theme-cayman