lsi: false
safe: true
source: https://github.com/johnmcbride/jwks.tools
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
github:
  zip_url: http://example.com/download.zip
  another_url: another value
theme: jekyll-theme-cayman